language: r
sudo: false
cache: packages
git:
  depth: false

script:
- Rscript -e 'rmarkdown::render("index.Rmd")'
- git config --global user.name "fawda123"
- git config --global user.email "mbafs2012@gmail.com"
- git pull https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:${TRAVIS_BRANCH}
- git add -A
- git commit -a -m "Updating index rmd build for website via travis-ci.org [ci skip]"
- git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:${TRAVIS_BRANCH}
notifications:
  email:
    recipients:
    - mbafs2012@gmail.com
    on_success: change
    on_failure: change
env:
  global:
  - TRAVIS_REPO_SLUG=tbep-tech/tbep-refs
  - TRAVIS_BRANCH=master
  - secure: T3ZEqTptdjCo2sFdz+OQAB1mq0CrLJB+MnTYZ40651W9GNqSo/WKNbkvMSBMNPfYnOab+13AiPcd6v2bEQXMWIKLGHqTLxq9k9sp3XPn6jNQzVftkRSsFgYze00MIUZi6eQoD1jHOXanfsazlHnqiI+swYGqoaNjya9vPd/vb7xO1/JecSiMoMHNCbBl2clfDBQ7b53tPGvlDLgSDSxj7SYjlVbrq2CQQsNTA5wbfuPEUNhJwBXvAnNnpE+T6Z/vFB6oWYHG5F0lUhlRSibqSSpoPh6cQb0ABTdTDUqRYf9+kHxvDAcNmdtkT/CTJFHxBgWdrSfKLdwiSSxBnwm08P/uo9LlkwF9nf2ra4nmzaJfI0yE5Edncb4fss7UMtalvhfI1DjyI1ZUkNnJmVNiDBHd0r+bp0p9Afvjpu7K9TGtXCJmrMOHEjjT60Ah8r78DEXJIONIDfK2D4B1JZMR0SbqfbDvnWB7PSMpe34NwPwxf8uDpkJt3v0QL4nkLeU793aeTDH9xUP6F/RCtw2AXAaEmWu3USG9E1npq6cXkHBVLqSRq/vNfHvKnWUM/WHFJtf77Ywd5IquBBFf89kErqfuAf9T/tfkr+b2md4YQXUGkKAM3P6RNea3UOnsBHgRmqjajZEmi86jrGwSmnNYVDznHAIWR7PmbmHp+vlFU/0=
  - CRAN: http://cran.rstudio.com